name = "timesheet-processor"
compatibility_date = "2023-12-23"

[build]
command = "npm run build"
publish = "out"

[[d1_databases]]
binding = "DB"
database_name = "timesheet-processor"
database_id = "77c632f9-fb38-4240-8217-00395bd5ca87"

[build.environment]
NODE_VERSION = "18"

[env.production]
NEXTAUTH_URL = "https://your-domain.pages.dev"
